#!/bin/bash
# ─────────────────────────────────────────────────────────
#  DGC RetailOS — Version Bump Script
#
#  Usage:
#    ./bump-version.sh            → auto bump patch  1.0.0 → 1.0.1
#    ./bump-version.sh minor      → bump minor       1.0.1 → 1.1.0
#    ./bump-version.sh major      → bump major       1.1.0 → 2.0.0
# ─────────────────────────────────────────────────────────

PACKAGE="frontend/package.json"
VERSION_JSON="version.json"
VERSION_PY="backend/version_info.py"
BUMP=${1:-patch}

# Read current version
CURRENT=$(node -p "require('./$PACKAGE').version" 2>/dev/null)
if [ -z "$CURRENT" ]; then
  echo "❌ Could not read version from $PACKAGE"
  exit 1
fi

IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

case "$BUMP" in
  major) NEW_VER="$((MAJOR+1)).0.0" ;;
  minor) NEW_VER="$MAJOR.$((MINOR+1)).0" ;;
  *)
    NEXT_PATCH=$((PATCH + 1))
    if [ "$NEXT_PATCH" -ge 100 ]; then
      # Patch 100+ rolls to next minor (1.0.x → 1.2.2 line, else e.g. 1.2.99 → 1.3.0)
      if [ "$MAJOR" = "1" ] && [ "$MINOR" = "0" ]; then
        NEW_VER="1.2.2"
      else
        NEW_VER="$MAJOR.$((MINOR + 1)).0"
      fi
    else
      NEW_VER="$MAJOR.$MINOR.$NEXT_PATCH"
    fi
    ;;
esac

BUILD_DATE=$(date +"%Y.%m.%d")
TODAY=$(date +"%Y-%m-%d")

echo "📦 Bumping version: $CURRENT → $NEW_VER  |  Build: $BUILD_DATE"

# Update package.json
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/\"version\": \"$CURRENT\"/\"version\": \"$NEW_VER\"/" "$PACKAGE"
else
  sed -i "s/\"version\": \"$CURRENT\"/\"version\": \"$NEW_VER\"/" "$PACKAGE"
fi

# Update / create version.json (read by backend /api/settings/version)
# Keep codename if it exists
if [ -f "$VERSION_JSON" ]; then
  CODENAME=$(node -p "try{require('./$VERSION_JSON').codename}catch(e){''}" 2>/dev/null)
else
  CODENAME="Sapphire"
fi

# On major bump, advance codename
if [ "$BUMP" = "major" ]; then
  declare -a NAMES=("Sapphire" "Emerald" "Ruby" "Diamond" "Onyx" "Pearl" "Topaz" "Amethyst")
  IDX=0
  for i in "${!NAMES[@]}"; do
    if [ "${NAMES[$i]}" = "$CODENAME" ]; then
      IDX=$(( (i + 1) % ${#NAMES[@]} ))
      break
    fi
  done
  CODENAME="${NAMES[$IDX]}"
fi

cat > "$VERSION_JSON" << JSON
{
  "version": "$NEW_VER",
  "build": "$BUILD_DATE",
  "codename": "$CODENAME",
  "created_by": "GuruShah",
  "released": "$TODAY"
}
JSON

# Update APP_VERSION in index.html cache-buster
INDEX_HTML="frontend/index.html"
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/var APP_VERSION = '[^']*'/var APP_VERSION = '$NEW_VER'/" "$INDEX_HTML"
else
  sed -i "s/var APP_VERSION = '[^']*'/var APP_VERSION = '$NEW_VER'/" "$INDEX_HTML"
fi

# Update backend/version_info.py (always bundled with Railway deployment)
cat > "$VERSION_PY" << PYEOF
# Auto-generated by bump-version.sh — DO NOT EDIT MANUALLY
VERSION_INFO = {
    "version":    "$NEW_VER",
    "build":      "$BUILD_DATE",
    "codename":   "$CODENAME",
    "created_by": "GuruShah",
    "released":   "$TODAY"
}
PYEOF

# Copy version.json to frontend/public/ so Cloudflare Pages / Vercel serves it for the SW watchdog
cp "$VERSION_JSON" "frontend/public/version.json"

echo "✅ Updated files:"
echo "   • $PACKAGE          → v$NEW_VER"
echo "   • $VERSION_JSON     → build $BUILD_DATE · $CODENAME"
echo "   • $VERSION_PY       → v$NEW_VER (Railway backend)"
echo "   • $INDEX_HTML       → APP_VERSION $NEW_VER (SW cache buster)"
echo "   • frontend/public/version.json → v$NEW_VER (SW watchdog)"
